FROM golang:1.22-alpine

WORKDIR /usr/src/app

# RUN adduser -D portal portal

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN go build  -v -o /usr/local/bin/portal ./cmd/server/main.go

EXPOSE 8080

# USER portal

CMD [ "portal" ]