FROM golang:1.23-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY .air.toml /app/.air.toml
# COPY pkg /app/pkg
# COPY cmd /app/cmd
COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]